import { Gift, HeartHandshake, Sparkles, Utensils, Waves, Wifi } from "lucide-react";
import { useLanguage } from "@/lib/i18n";

export function Offers() {
  const { language } = useLanguage();
  const offers = language === "vi" ? [{ title: "Ở 3 đêm, tặng 1 đêm", desc: "Áp dụng tại Sen Việt Đà Nẵng và Nha Trang.", tag: "HOT" }, { title: "Ưu đãi thành viên Sen Việt", desc: "Giảm 15% giá phòng và nhận phòng sớm.", tag: "MEMBER" }, { title: "Trọn gói cuối tuần", desc: "Phòng, bữa sáng và trải nghiệm địa phương.", tag: "NEW" }] : [{ title: "Stay 3 nights, get 1 free", desc: "Available at Sen Việt Da Nang and Nha Trang.", tag: "HOT" }, { title: "Sen Việt member offer", desc: "15% off rooms plus early check-in.", tag: "MEMBER" }, { title: "Weekend escape", desc: "Room, breakfast and a local experience.", tag: "NEW" }];
  return <main className="container py-16"><p className="text-sm font-semibold uppercase tracking-[.16em] text-gold">Sen Việt benefits</p><h1 className="mt-3 font-display text-5xl font-bold text-primary">{language === "vi" ? "Ưu đãi dành riêng cho bạn" : "Offers made for you"}</h1><div className="mt-10 grid gap-6 md:grid-cols-3">{offers.map((offer) => <article key={offer.title} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-secondary text-primary"><Gift className="h-5 w-5" /></div><span className="rounded-full bg-gold px-3 py-1 text-xs font-bold text-gold-foreground">{offer.tag}</span></div><h2 className="mt-6 font-display text-2xl font-bold text-primary">{offer.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{offer.desc}</p><button className="mt-6 rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{language === "vi" ? "Xem ưu đãi" : "View offer"}</button></article>)}</div></main>;
}

export function Services() {
  const { language } = useLanguage();
  const services = language === "vi" ? [[HeartHandshake, "Chăm sóc khách hàng 24/7", "Trợ lý AI và đội ngũ Sen Việt luôn sẵn sàng hỗ trợ."], [Utensils, "Ẩm thực bản địa", "Thưởng thức hương vị đặc trưng tại nhà hàng trong khách sạn."], [Waves, "Nghỉ dưỡng & spa", "Tái tạo năng lượng với hồ bơi, spa và các liệu trình thư giãn."], [Wifi, "Không gian làm việc", "Wi-Fi tốc độ cao và phòng họp cho mọi nhu cầu công việc."]] : [[HeartHandshake, "24/7 guest care", "Our AI assistant and guest team are always here to help."], [Utensils, "Local cuisine", "Discover regional flavors at our in-house restaurants."], [Waves, "Wellness & spa", "Recharge with pools, spas and relaxing treatments."], [Wifi, "Work spaces", "High-speed Wi-Fi and meeting rooms for every work need."]];
  return <main className="container py-16"><p className="text-sm font-semibold uppercase tracking-[.16em] text-gold">Sen Việt hospitality</p><h1 className="mt-3 font-display text-5xl font-bold text-primary">{language === "vi" ? "Dịch vụ của Sen Việt" : "Sen Việt services"}</h1><div className="mt-10 grid gap-5 sm:grid-cols-2">{services.map(([Icon,title,desc]) => <article key={title as string} className="flex gap-4 rounded-2xl border border-border bg-card p-6"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="h-6 w-6" /></div><div><h2 className="font-display text-xl font-bold text-primary">{title as string}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{desc as string}</p></div></article>)}</div></main>;
}
