import { FormEvent, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { CheckCircle2, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getBookings } from "@/lib/bookings";
import { saveReview } from "@/lib/customer";
import { useAuth } from "@/lib/auth";

export default function ReviewPage() { const { bookingId } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const booking = getBookings().find((item) => item.id === bookingId && item.userEmail === user?.email); const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); const [sent, setSent] = useState(false); if (!booking) return <main className="container py-20 text-center"><h1 className="font-display text-3xl font-bold text-primary">Không tìm thấy booking</h1><Button asChild className="mt-5 rounded-full"><Link to="/bookings">Về lịch sử đặt phòng</Link></Button></main>; if (booking.status !== "completed") return <main className="container py-20 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-primary" /><h1 className="mt-5 font-display text-3xl font-bold text-primary">Chưa thể đánh giá</h1><p className="mx-auto mt-3 max-w-md text-muted-foreground">Bạn chỉ có thể đánh giá sau khi đã hoàn tất check-out tại khách sạn.</p><Button asChild className="mt-5 rounded-full"><Link to="/bookings">Về lịch sử đặt phòng</Link></Button></main>; const submit = (event: FormEvent) => { event.preventDefault(); saveReview({ id: `REV-${Date.now()}`, bookingId: booking.id, userEmail: user?.email || "", hotelSlug: booking.hotelSlug, rating, comment, createdAt: new Date().toISOString(), status: "pending" }); setSent(true); }; if (sent) return <main className="container flex min-h-[55vh] flex-col items-center justify-center py-20 text-center"><CheckCircle2 className="h-12 w-12 text-emerald-600" /><h1 className="mt-5 font-display text-3xl font-bold text-primary">Cảm ơn bạn đã đánh giá</h1><p className="mt-3 text-muted-foreground">Đánh giá của bạn giúp Sen Việt phục vụ tốt hơn.</p><Button onClick={() => navigate("/bookings")} className="mt-5 rounded-full">Về lịch sử đặt phòng</Button></main>; return <main className="container py-16"><form onSubmit={submit} className="mx-auto max-w-xl rounded-3xl border border-border bg-card p-8 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[.16em] text-gold">Completed stay</p><h1 className="mt-3 font-display text-3xl font-bold text-primary">Đánh giá {booking.hotelName}</h1><p className="mt-2 text-sm text-muted-foreground">{booking.roomName} · {booking.checkIn} → {booking.checkOut}</p><div className="mt-8 flex gap-2">{[1, 2, 3, 4, 5].map((value) => <button type="button" key={value} onClick={() => setRating(value)} aria-label={`${value} sao`}><Star className={`h-8 w-8 ${value <= rating ? "fill-gold text-gold" : "text-muted"}`} /></button>)}</div><label className="mt-6 block text-sm font-medium text-primary">Chia sẻ trải nghiệm<textarea required value={comment} onChange={(e) => setComment(e.target.value)} className="mt-2 min-h-32 w-full rounded-xl border border-input p-3" placeholder="Phòng, dịch vụ, nhân viên..." /></label><Button type="submit" className="mt-6 w-full rounded-xl">Gửi đánh giá</Button></form></main>; }
